name: Generate JSON Blog Posts

on:
  push:
    paths:
      - 'blog/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Convert HTML files to JSON
        run: |
          mkdir -p json
          echo "[" > index.json

          for file in blog/*.html; do
            FILENAME=$(basename "$file" .html)
            TITLE=$(grep -oP '(?<=<h1>).*?(?=</h1>)' "$file" | head -1)
            DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            # escape content
            CONTENT=$(cat "$file" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')

            JSON_CONTENT="{\"slug\":\"$FILENAME\",\"title\":\"$TITLE\",\"date\":\"$DATE\",\"content\":\"$CONTENT\"}"

            echo "$JSON_CONTENT" > "json/$FILENAME.json"

            echo "  {\"slug\":\"$FILENAME\",\"title\":\"$TITLE\",\"date\":\"$DATE\"}," >> index.json
          done

          # remove last comma from index
          sed -i '$ s/,$//' index.json
          echo "]" >> index.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add json/*.json index.json
          git commit -m "Update JSON blog posts" || echo "No changes to commit"
          git push
