name: Generate JSON Blog Posts

on:
  push:
    paths:
      - 'blog/*.html'
      - 'images/**'
      - '.github/workflows/generate-json.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Rewrite image paths in HTML
        run: |
          GITHUB_USER="shivamsancc"    # 🔁 Replace with your GitHub username
          GITHUB_REPO="blogs"          # 🔁 Replace with your repo name
          BRANCH="main"

          RAW_BASE="https://raw.githubusercontent.com/$GITHUB_USER/$GITHUB_REPO/$BRANCH/images"

          mkdir -p tmp_blog
          for file in blog/*.html; do
            OUT="tmp_blog/$(basename "$file")"
            sed -E "s|<img([^>]*?)src=[\"']\.{0,2}/?images/([^\"']+)[\"']|<img\1src=\"$RAW_BASE/\2\"|g" "$file" > "$OUT"
          done

      - name: Convert HTML to JSON using jq
        run: |
          mkdir -p json
          echo "[" > index.json

          FIRST=1
          for file in tmp_blog/*.html; do
            FILENAME=$(basename "$file" .html)
            TITLE=$(grep -oP '(?<=<h1>).*?(?=</h1>)' "$file" | head -1)
            DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            CONTENT=$(cat "$file")

            # Write full post JSON
            jq -n \
              --arg slug "$FILENAME" \
              --arg title "$TITLE" \
              --arg date "$DATE" \
              --arg content "$CONTENT" \
              '{slug: $slug, title: $title, date: $date, content: $content}' > "json/$FILENAME.json"

            # Append to index.json
            if [ $FIRST -eq 0 ]; then echo "," >> index.json; fi
            FIRST=0

            jq -n \
              --arg slug "$FILENAME" \
              --arg title "$TITLE" \
              --arg date "$DATE" \
              '{slug: $slug, title: $title, date: $date}' >> index.json
          done

          echo "]" >> index.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add json/*.json index.json
          git commit -m "Update JSON blog posts with fixed image paths" || echo "No changes to commit"
          git push
